### ISSUE TITLE
7.	UI template update for “Theses” and “Reports” (Minor issue)

### ISSUE THREAD

**Issue by jcreel** [TAMULib/scholars-discovery#195] opened 2022-11-15 21:05 UTC
a.	Data property: http://www.w3.org/2006/vcard/ns#note 
b.	Data:
i.	Thesis: https://vivo.library.tamu.edu/vivo/display/n401399SE
ii.	Report: https://vivo.library.tamu.edu/vivo/display/n286121SE 
c.	If data is available, add  “ – note” (where "note" is the data in the field)
d.	Use the same template of “Internet Publications”
 

![Image](https://user-images.githubusercontent.com/8352733/200897901-d7aa1578-3c56-459d-b65f-a634e0e13f0e.png)

**Comment by ghost** [comment] 2022-12-29 14:22
Duplicate of https://github.com/TAMULib/scholars-discovery/issues/169

**Closed as completed** 2023-01-06 22:01 UTC
